
export const countries = [
    { label: "United States", value: "US", flag: "🇺🇸" },
    { label: "United Kingdom", value: "GB", flag: "🇬🇧" },
    { label: "Canada", value: "CA", flag: "🇨🇦" },
    { label: "Australia", value: "AU", flag: "🇦🇺" },
    { label: "Germany", value: "DE", flag: "🇩🇪" },
    { label: "France", value: "FR", flag: "🇫🇷" },
    { label: "Italy", value: "IT", flag: "🇮🇹" },
    { label: "Spain", value: "ES", flag: "🇪🇸" },
    { label: "Japan", value: "JP", flag: "🇯🇵" },
    { label: "South Korea", value: "KR", flag: "🇰🇷" },
    { label: "China", value: "CN", flag: "🇨🇳" },
    { label: "India", value: "IN", flag: "🇮🇳" },
    { label: "Brazil", value: "BR", flag: "🇧🇷" },
    { label: "Mexico", value: "MX", flag: "🇲🇽" },
    { label: "South Africa", value: "ZA", flag: "🇿🇦" },
    { label: "Nigeria", value: "NG", flag: "🇳🇬" },
    { label: "Kenya", value: "KE", flag: "🇰🇪" },
    { label: "Ghana", value: "GH", flag: "🇬🇭" },
    { label: "Egypt", value: "EG", flag: "🇪🇬" },
    { label: "United Arab Emirates", value: "AE", flag: "🇦🇪" },
    { label: "Netherlands", value: "NL", flag: "🇳🇱" },
    { label: "Sweden", value: "SE", flag: "🇸🇪" },
    { label: "Switzerland", value: "CH", flag: "🇨🇭" },
    { label: "New Zealand", value: "NZ", flag: "🇳🇿" },
    { label: "Singapore", value: "SG", flag: "🇸🇬" },
    { label: "Thailand", value: "TH", flag: "🇹🇭" },
    { label: "Vietnam", value: "VN", flag: "🇻🇳" },
    { label: "Indonesia", value: "ID", flag: "🇮🇩" },
    { label: "Malaysia", value: "MY", flag: "🇲🇾" },
    { label: "Philippines", value: "PH", flag: "🇵🇭" },
    { label: "Turkey", value: "TR", flag: "🇹🇷" },
    { label: "Greece", value: "GR", flag: "🇬🇷" },
    { label: "Portugal", value: "PT", flag: "🇵🇹" },
    { label: "Ireland", value: "IE", flag: "🇮🇪" },
    { label: "Poland", value: "PL", flag: "🇵🇱" },
    { label: "Austria", value: "AT", flag: "🇦🇹" },
    { label: "Belgium", value: "BE", flag: "🇧🇪" },
    { label: "Denmark", value: "DK", flag: "🇩🇰" },
    { label: "Norway", value: "NO", flag: "🇳🇴" },
    { label: "Finland", value: "FI", flag: "🇫🇮" },
    { label: "Russia", value: "RU", flag: "🇷🇺" },
    { label: "Ukraine", value: "UA", flag: "🇺🇦" },
    { label: "Czech Republic", value: "CZ", flag: "🇨🇿" },
    { label: "Hungary", value: "HU", flag: "🇭🇺" },
    { label: "Romania", value: "RO", flag: "🇷🇴" },
    { label: "Saudi Arabia", value: "SA", flag: "🇸🇦" },
    { label: "Israel", value: "IL", flag: "🇮🇱" },
    { label: "Argentina", value: "AR", flag: "🇦🇷" },
    { label: "Chile", value: "CL", flag: "🇨🇱" },
    { label: "Colombia", value: "CO", flag: "🇨🇴" },
    { label: "Peru", value: "PE", flag: "🇵🇪" }
] as const;

export function getCountryByCode(code: string) {
    return countries.find((c) => c.value === code) || null;
}
